// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings
#ifndef DISABLE_CIMPLOT
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#include "implot.h"

// Wrap this in a namespace to keep it separate from the C++ API
namespace c
{
#include "cimplot.h"
}

// By-value struct conversions

// Function stubs

#define FCAST(x, y) reinterpret_cast<x>(y)
#define TMPCAST(x, y)       \
    auto a = x;             \
    return *FCAST(y*, &a)

#ifndef IMGUI_DISABLE
extern "C"
{
CIMGUI_API bool   ImPlotRange_Contains(const c::ImPlotRange* self, const double value)
{
    return reinterpret_cast<const ::ImPlotRange*>(self)->Contains(value);
}

CIMGUI_API double ImPlotRange_Size(const c::ImPlotRange* self)
{
    return reinterpret_cast<const ::ImPlotRange*>(self)->Size();
}

CIMGUI_API double ImPlotRange_Clamp(const c::ImPlotRange* self, const double value)
{
    return reinterpret_cast<const ::ImPlotRange*>(self)->Clamp(value);
}

CIMGUI_API bool        ImPlotRect_Contains(const c::ImPlotRect* self, const c::ImPlotPoint p)
{
    return reinterpret_cast<const ::ImPlotRect*>(self)->Contains(reinterpret_cast<const ::ImPlotPoint&>(p));
}

CIMGUI_API bool        ImPlotRect_ContainsDouble(const c::ImPlotRect* self, const double x, const double y)
{
    return reinterpret_cast<const ::ImPlotRect*>(self)->Contains(x, y);
}

#define CALL_PLOT_RECT_CONST(x, ...)                                    \
auto tmp = reinterpret_cast<const ::ImPlotRect*>(self)->x(__VA_ARGS__);    \
return *reinterpret_cast<c::ImPlotPoint*>(&tmp)

#define CALL_PLOT_RECT(x, ...)                                    \
auto tmp = reinterpret_cast<::ImPlotRect*>(self)->x(__VA_ARGS__);    \
return *reinterpret_cast<c::ImPlotPoint*>(&tmp)

CIMGUI_API c::ImPlotPoint ImPlotRect_Size(const c::ImPlotRect* self)
{
    CALL_PLOT_RECT_CONST(Size);
}

CIMGUI_API c::ImPlotPoint ImPlotRect_Clamp(c::ImPlotRect* self, const c::ImPlotPoint p)
{
    CALL_PLOT_RECT(Clamp, *reinterpret_cast<const ::ImPlotPoint*>(&p));
}

CIMGUI_API c::ImPlotPoint ImPlotRect_ClampDouble(c::ImPlotRect* self, const double x, const double y)
{
    CALL_PLOT_RECT(Clamp, x, y);
}

CIMGUI_API c::ImPlotPoint ImPlotRect_Min(const c::ImPlotRect* self)
{
    CALL_PLOT_RECT_CONST(Min);
}

CIMGUI_API c::ImPlotPoint ImPlotRect_Max(const c::ImPlotRect* self)
{
    CALL_PLOT_RECT_CONST(Max);
}

CIMGUI_API c::ImPlotContext* ImPlot_CreateContext()
{
    return reinterpret_cast <c::ImPlotContext*>(::ImPlot::CreateContext());
}

CIMGUI_API void           ImPlot_DestroyContext()
{
    ::ImPlot::DestroyContext();
}

CIMGUI_API void           ImPlot_DestroyContextEx(c::ImPlotContext* ctx)
{
    ::ImPlot::DestroyContext(reinterpret_cast<::ImPlotContext*>(ctx));
}

CIMGUI_API c::ImPlotContext* ImPlot_GetCurrentContext()
{
    return reinterpret_cast<c::ImPlotContext*>(::ImPlot::GetCurrentContext());
}

CIMGUI_API void           ImPlot_SetCurrentContext(c::ImPlotContext* ctx)
{
    ::ImPlot::SetCurrentContext(reinterpret_cast<::ImPlotContext*>(ctx));
}

CIMGUI_API void ImPlot_SetImGuiContext(c::ImGuiContext* ctx)
{
    ::ImPlot::SetImGuiContext(reinterpret_cast<::ImGuiContext*>(ctx));
}

CIMGUI_API bool ImPlot_BeginPlot(const char* title_id)
{
    return ::ImPlot::BeginPlot(title_id);
}

CIMGUI_API bool ImPlot_BeginPlotEx(const char* title_id, const c::ImVec2 size, const c::ImPlotFlags flags)
{
    return ::ImPlot::BeginPlot(title_id, reinterpret_cast<const ::ImVec2&>(size), flags);
}

CIMGUI_API void ImPlot_EndPlot()
{
    ::ImPlot::EndPlot();
}

CIMGUI_API bool ImPlot_BeginSubplots(const char* title_id, const int rows, const int cols, const c::ImVec2 size, const c::ImPlotSubplotFlags flags)
{
    return ::ImPlot::BeginSubplots(title_id, rows, cols, reinterpret_cast<const ::ImVec2&>(size), flags);
}

CIMGUI_API bool ImPlot_BeginSubplotsEx(const char* title_id, const int rows, const int cols, const c::ImVec2 size, const c::ImPlotSubplotFlags flags, float* row_ratios, float* col_ratios)
{
    return ::ImPlot::BeginSubplots(title_id, rows, cols, reinterpret_cast<const ::ImVec2&>(size), flags, row_ratios, col_ratios);
}

CIMGUI_API void ImPlot_EndSubplots()
{
    ::ImPlot::EndSubplots();
}

CIMGUI_API void ImPlot_SetupAxis(const c::ImAxis axis)
{
    ::ImPlot::SetupAxis(axis);
}

CIMGUI_API void ImPlot_SetupAxisEx(const c::ImAxis axis, const char* label, const c::ImPlotAxisFlags flags)
{
    ::ImPlot::SetupAxis(axis, label, flags);
}

CIMGUI_API void ImPlot_SetupAxisLimits(const c::ImAxis axis, const double v_min, const double v_max)
{
    ::ImPlot::SetupAxisLimits(axis, v_min, v_max);
}

CIMGUI_API void ImPlot_SetupAxisLimitsEx(const c::ImAxis axis, const double v_min, const double v_max, const c::ImPlotCond cond)
{
    ::ImPlot::SetupAxisLimits(axis, v_min, v_max, cond);
}

CIMGUI_API void ImPlot_SetupAxisLinks(const c::ImAxis axis, double* link_min, double* link_max)
{
    ::ImPlot::SetupAxisLinks(axis, link_min, link_max);
}

CIMGUI_API void ImPlot_SetupAxisFormat(const c::ImAxis axis, const char* fmt)
{
    ::ImPlot::SetupAxisFormat(axis, fmt);
}

CIMGUI_API void ImPlot_SetupAxisFormatImPlotFormatter(const c::ImAxis axis, const c::ImPlotFormatter formatter)
{
    ::ImPlot::SetupAxisFormat(axis, reinterpret_cast<::ImPlotFormatter>(formatter));
}

CIMGUI_API void ImPlot_SetupAxisFormatImPlotFormatterEx(const c::ImAxis axis, const c::ImPlotFormatter formatter, void* data)
{
    ::ImPlot::SetupAxisFormat(axis, reinterpret_cast<::ImPlotFormatter>(formatter), data);
}

CIMGUI_API void ImPlot_SetupAxisTicks(const c::ImAxis axis, const double* values, const int n_ticks)
{
    ::ImPlot::SetupAxisTicks(axis, values, n_ticks);
}

CIMGUI_API void ImPlot_SetupAxisTicksEx(const c::ImAxis axis, const double* values, const int n_ticks, const char*const labels[], const bool keep_default)
{
    ::ImPlot::SetupAxisTicks(axis, values, n_ticks, labels, keep_default);
}

CIMGUI_API void ImPlot_SetupAxisTicksDouble(const c::ImAxis axis, double const v_min, double const v_max, const int n_ticks)
{
    ::ImPlot::SetupAxisTicks(axis, v_min, v_max, n_ticks);
}

CIMGUI_API void ImPlot_SetupAxisTicksDoubleEx(const c::ImAxis axis, const double v_min, const double v_max, const int n_ticks, const char*const labels[], const bool keep_default)
{
    ::ImPlot::SetupAxisTicks(axis, v_min, v_max, n_ticks, labels, keep_default);
}

CIMGUI_API void ImPlot_SetupAxisScale(const c::ImAxis axis, const c::ImPlotScale scale)
{
    ::ImPlot::SetupAxisScale(axis, scale);
}

CIMGUI_API void ImPlot_SetupAxisScaleImPlotTransform(const c::ImAxis axis, const c::ImPlotTransform forward, const c::ImPlotTransform inverse)
{
    ::ImPlot::SetupAxisScale(axis, reinterpret_cast<::ImPlotTransform>(forward), reinterpret_cast<::ImPlotTransform>(inverse));
}

CIMGUI_API void ImPlot_SetupAxisScaleImPlotTransformEx(const c::ImAxis axis, const c::ImPlotTransform forward, const c::ImPlotTransform inverse, void* data)
{
    ::ImPlot::SetupAxisScale(axis, reinterpret_cast<::ImPlotTransform>(forward), reinterpret_cast<::ImPlotTransform>(inverse), data);
}

CIMGUI_API void ImPlot_SetupAxisLimitsConstraints(const c::ImAxis axis, const double v_min, const double v_max)
{
    ::ImPlot::SetupAxisLimitsConstraints(axis, v_min, v_max);
}

CIMGUI_API void ImPlot_SetupAxisZoomConstraints(const c::ImAxis axis, const double z_min, const double z_max)
{
    ::ImPlot::SetupAxisZoomConstraints(axis, z_min, z_max);
}

CIMGUI_API void ImPlot_SetupAxes(const char* x_label, const char* y_label)
{
    ::ImPlot::SetupAxes(x_label, y_label);
}

CIMGUI_API void ImPlot_SetupAxesEx(const char* x_label, const char* y_label, const c::ImPlotAxisFlags x_flags, const c::ImPlotAxisFlags y_flags)
{
    ::ImPlot::SetupAxes(x_label, y_label, x_flags, y_flags);
}

CIMGUI_API void ImPlot_SetupAxesLimits(const double x_min, const double x_max, const double y_min, const double y_max)
{
    ::ImPlot::SetupAxesLimits(x_min, x_max, y_min, y_max);
}

CIMGUI_API void ImPlot_SetupAxesLimitsEx(const double x_min, const double x_max, const double y_min, const double y_max, const c::ImPlotCond cond)
{
    ::ImPlot::SetupAxesLimits(x_min, x_max, y_min, y_max, cond);
}

CIMGUI_API void ImPlot_SetupLegend(const c::ImPlotLocation location, const c::ImPlotLegendFlags flags)
{
    ::ImPlot::SetupLegend(location, flags);
}

CIMGUI_API void ImPlot_SetupMouseText(const c::ImPlotLocation location, const c::ImPlotMouseTextFlags flags)
{
    ::ImPlot::SetupMouseText(location, flags);
}

CIMGUI_API void ImPlot_SetupFinish()
{
    ::ImPlot::SetupFinish();
}

CIMGUI_API void ImPlot_SetNextAxisLimits(const c::ImAxis axis, const double v_min, const double v_max)
{
    ::ImPlot::SetNextAxisLimits(axis, v_min, v_max);
}

CIMGUI_API void ImPlot_SetNextAxisLimitsEx(const c::ImAxis axis, const double v_min, const double v_max, const c::ImPlotCond cond)
{
    ::ImPlot::SetNextAxisLimits(axis, v_min, v_max, cond);
}

CIMGUI_API void ImPlot_SetNextAxisLinks(const c::ImAxis axis, double* link_min, double* link_max)
{
    ::ImPlot::SetNextAxisLinks(axis, link_min, link_max);
}

CIMGUI_API void ImPlot_SetNextAxisToFit(const c::ImAxis axis)
{
    ::ImPlot::SetNextAxisToFit(axis);
}

CIMGUI_API void ImPlot_SetNextAxesLimits(const double x_min, const double x_max, const double y_min, const double y_max)
{
    ::ImPlot::SetNextAxesLimits(x_min, x_max, y_min, y_max);
}

CIMGUI_API void ImPlot_SetNextAxesLimitsEx(const double x_min, const double x_max, const double y_min, const double y_max, const c::ImPlotCond cond)
{
    ::ImPlot::SetNextAxesLimits(x_min, x_max, y_min, y_max, cond);
}

CIMGUI_API void ImPlot_SetNextAxesToFit()
{
    ::ImPlot::SetNextAxesToFit();
}

CIMGUI_API void ImPlot_PlotLineInt(const char* label_id, const double* values, const int count)
{
    ::ImPlot::PlotLine(label_id, values, count);
}

CIMGUI_API void ImPlot_PlotLineIntEx(const char* label_id, const double* values, const int count, const double xscale, const double xstart, const c::ImPlotLineFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotLine(label_id, values, count, xscale, xstart, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotLine(const char* label_id, const double* xs, const double* ys, const int count, const c::ImPlotLineFlags flags)
{
    ::ImPlot::PlotLine(label_id, xs, ys, count, flags);
}

CIMGUI_API void ImPlot_PlotLineEx(const char* label_id, const double* xs, const double* ys, const int count, const c::ImPlotLineFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotLine(label_id, xs, ys, count, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotLineG(const char* label_id, const c::ImPlotGetter getter, void* data, const int count, const c::ImPlotLineFlags flags)
{
    ::ImPlot::PlotLineG(label_id, reinterpret_cast<::ImPlotGetter>(getter), data, count, flags);
}

CIMGUI_API void ImPlot_PlotScatterInt(const char* label_id, const double* values, const int count)
{
    ::ImPlot::PlotScatter(label_id, values, count);
}

CIMGUI_API void ImPlot_PlotScatterIntEx(const char* label_id, const double* values, const int count, const double xscale, const double xstart, const c::ImPlotScatterFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotScatter(label_id, values, count, xscale, xstart, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotScatter(const char* label_id, const double* xs, const double* ys, const int count, const c::ImPlotScatterFlags flags)
{
    ::ImPlot::PlotScatter(label_id, xs, ys, count, flags);
}

CIMGUI_API void ImPlot_PlotScatterEx(const char* label_id, const double* xs, const double* ys, const int count, const c::ImPlotScatterFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotScatter(label_id, xs, ys, count, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotScatterG(const char* label_id, const c::ImPlotGetter getter, void* data, const int count, const c::ImPlotScatterFlags flags)
{
    ::ImPlot::PlotScatterG(label_id, reinterpret_cast<::ImPlotGetter>(getter), data, count, flags);
}

CIMGUI_API void ImPlot_PlotStairsInt(const char* label_id, const double* values, const int count)
{
    ::ImPlot::PlotStairs(label_id, values, count);
}

CIMGUI_API void ImPlot_PlotStairsIntEx(const char* label_id, const double* values, const int count, const double xscale, const double xstart, const c::ImPlotStairsFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotStairs(label_id, values, count, xscale, xstart, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotStairs(const char* label_id, const double* xs, const double* ys, const int count, const c::ImPlotStairsFlags flags)
{
    ::ImPlot::PlotStairs(label_id, xs, ys, count, flags);
}

CIMGUI_API void ImPlot_PlotStairsEx(const char* label_id, const double* xs, const double* ys, const int count, const c::ImPlotStairsFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotStairs(label_id, xs, ys, count, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotStairsG(const char* label_id, const c::ImPlotGetter getter, void* data, const int count, const c::ImPlotStairsFlags flags)
{
    ::ImPlot::PlotStairsG(label_id, reinterpret_cast<::ImPlotGetter>(getter), data, count, flags);
}

CIMGUI_API void ImPlot_PlotShadedInt(const char* label_id, const double* values, const int count)
{
    ::ImPlot::PlotShaded(label_id, values, count);
}

CIMGUI_API void ImPlot_PlotShadedIntEx(const char* label_id, const double* values, const int count, const double yref, const double xscale, const double xstart, const c::ImPlotShadedFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotShaded(label_id, values, count, yref, xscale, xstart, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotShaded(const char* label_id, const double* xs, const double* ys, const int count)
{
    ::ImPlot::PlotShaded(label_id, xs, ys, count);
}

CIMGUI_API void ImPlot_PlotShadedEx(const char* label_id, const double* xs, const double* ys, const int count, const double yref, const c::ImPlotShadedFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotShaded(label_id, xs, ys, count, yref, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotShadedTPtr(const char* label_id, const double* xs, const double* ys1, const double* ys2, const int count, const c::ImPlotShadedFlags flags)
{
    ::ImPlot::PlotShaded(label_id, xs, ys1, ys2, count, flags);
}

CIMGUI_API void ImPlot_PlotShadedTPtrEx(const char* label_id, const double* xs, const double* ys1, const double* ys2, const int count, const c::ImPlotShadedFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotShaded(label_id, xs, ys1, ys2, count, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotShadedG(const char* label_id, const c::ImPlotGetter getter1, void* data1, const c::ImPlotGetter getter2, void* data2, const int count, const c::ImPlotShadedFlags flags)
{
    ::ImPlot::PlotShadedG(label_id, reinterpret_cast<::ImPlotGetter>(getter1), data1, reinterpret_cast<::ImPlotGetter>(getter2), data2, count, flags);
}

CIMGUI_API void ImPlot_PlotBars(const char* label_id, const double* values, const int count)
{
    ::ImPlot::PlotBars(label_id, values, count);
}

CIMGUI_API void ImPlot_PlotBarsEx(const char* label_id, const double* values, const int count, const double bar_size, const double shift, const c::ImPlotBarsFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotBars(label_id, values, count, bar_size, shift, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotBarsTPtr(const char* label_id, const double* xs, const double* ys, const int count, const double bar_size, const c::ImPlotBarsFlags flags)
{
    ::ImPlot::PlotBars(label_id, xs, ys, count, bar_size, flags);
}

CIMGUI_API void ImPlot_PlotBarsTPtrEx(const char* label_id, const double* xs, const double* ys, const int count, const double bar_size, const c::ImPlotBarsFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotBars(label_id, xs, ys, count, bar_size, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotBarsG(const char* label_id, const c::ImPlotGetter getter, void* data, const int count, const double bar_size, const c::ImPlotBarsFlags flags)
{
    ::ImPlot::PlotBarsG(label_id, reinterpret_cast<::ImPlotGetter>(getter), data, count, bar_size, flags);
}

CIMGUI_API void ImPlot_PlotBarGroups(const char*const label_ids[], const double* values, const int item_count, const int group_count)
{
    ::ImPlot::PlotBarGroups(label_ids, values, item_count, group_count);
}

CIMGUI_API void ImPlot_PlotBarGroupsEx(const char*const label_ids[], const double* values, const int item_count, const int group_count, const double group_size, const double shift, const c::ImPlotBarGroupsFlags flags)
{
    ::ImPlot::PlotBarGroups(label_ids, values, item_count, group_count, group_size, shift, flags);
}

CIMGUI_API void ImPlot_PlotErrorBars(const char* label_id, const double* xs, const double* ys, const double* err, const int count, const c::ImPlotErrorBarsFlags flags)
{
    ::ImPlot::PlotErrorBars(label_id, xs, ys, err, count, flags);
}

CIMGUI_API void ImPlot_PlotErrorBarsEx(const char* label_id, const double* xs, const double* ys, const double* err, const int count, const c::ImPlotErrorBarsFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotErrorBars(label_id, xs, ys, err, count, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotErrorBarsTPtr(const char* label_id, const double* xs, const double* ys, const double* neg, const double* pos, const int count, const c::ImPlotErrorBarsFlags flags)
{
    ::ImPlot::PlotErrorBars(label_id, xs, ys, neg, pos, count, flags);
}

CIMGUI_API void ImPlot_PlotErrorBarsTPtrEx(const char* label_id, const double* xs, const double* ys, const double* neg, const double* pos, const int count, const c::ImPlotErrorBarsFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotErrorBars(label_id, xs, ys, neg, pos, count, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotStemsInt(const char* label_id, const double* values, const int count)
{
    ::ImPlot::PlotStems(label_id, values, count);
}

CIMGUI_API void ImPlot_PlotStemsIntEx(const char* label_id, const double* values, const int count, const double ref, const double scale, const double start, const c::ImPlotStemsFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotStems(label_id, values, count, ref, scale, start, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotStems(const char* label_id, const double* xs, const double* ys, const int count)
{
    ::ImPlot::PlotStems(label_id, xs, ys, count);
}

CIMGUI_API void ImPlot_PlotStemsEx(const char* label_id, const double* xs, const double* ys, const int count, const double ref, const c::ImPlotStemsFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotStems(label_id, xs, ys, count, ref, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotInfLines(const char* label_id, const double* values, const int count, const c::ImPlotInfLinesFlags flags)
{
    ::ImPlot::PlotInfLines(label_id, values, count, flags);
}

CIMGUI_API void ImPlot_PlotInfLinesEx(const char* label_id, const double* values, const int count, const c::ImPlotInfLinesFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotInfLines(label_id, values, count, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotPieChartImPlotFormatter(const char*const label_ids[], const double* values, const int count, const double x, const double y, const double radius, const c::ImPlotFormatter fmt)
{
    ::ImPlot::PlotPieChart(label_ids, values, count, x, y, radius, reinterpret_cast<::ImPlotFormatter>(fmt));
}

CIMGUI_API void ImPlot_PlotPieChartImPlotFormatterEx(const char*const label_ids[], const double* values, const int count, const double x, const double y, const double radius, const c::ImPlotFormatter fmt, void* fmt_data, const double angle0, const c::ImPlotPieChartFlags flags)
{
    ::ImPlot::PlotPieChart(label_ids, values, count, x, y, radius, reinterpret_cast<::ImPlotFormatter>(fmt), fmt_data, angle0, flags);
}

CIMGUI_API void ImPlot_PlotPieChart(const char*const label_ids[], const double* values, const int count, const double x, const double y, const double radius)
{
    ::ImPlot::PlotPieChart(label_ids, values, count, x, y, radius);
}

CIMGUI_API void ImPlot_PlotPieChartEx(const char*const label_ids[], const double* values, const int count, const double x, const double y, const double radius, const char* label_fmt, const double angle0, const c::ImPlotPieChartFlags flags)
{
    ::ImPlot::PlotPieChart(label_ids, values, count, x, y, radius, label_fmt, angle0, flags);
}

CIMGUI_API void ImPlot_PlotHeatmap(const char* label_id, const double* values, const int rows, const int cols)
{
    ::ImPlot::PlotHeatmap(label_id, values, rows, cols);
}

CIMGUI_API void ImPlot_PlotHeatmapEx(const char* label_id, const double* values, const int rows, const int cols, const double scale_min, const double scale_max, const char* label_fmt, const c::ImPlotPoint bounds_min, const c::ImPlotPoint bounds_max, const c::ImPlotHeatmapFlags flags)
{
    ::ImPlot::PlotHeatmap(label_id, values, rows, cols, scale_min, scale_max, label_fmt, reinterpret_cast<const ::ImPlotPoint&>(bounds_min), reinterpret_cast<const ::ImPlotPoint&>(bounds_max), flags);
}

CIMGUI_API double ImPlot_PlotHistogram(const char* label_id, const double* values, const int count)
{
    return ::ImPlot::PlotHistogram(label_id, values, count);
}

CIMGUI_API double ImPlot_PlotHistogramEx(const char* label_id, const double* values, const int count, const int bins, const double bar_scale, c::ImPlotRange range, const c::ImPlotHistogramFlags flags)
{
    return ::ImPlot::PlotHistogram(label_id, values, count, bins, bar_scale, *reinterpret_cast<::ImPlotRange*>(&range), flags);
}

CIMGUI_API double ImPlot_PlotHistogram2D(const char* label_id, const double* xs, const double* ys, const int count)
{
    return ::ImPlot::PlotHistogram2D(label_id, xs, ys, count);
}

CIMGUI_API double ImPlot_PlotHistogram2DEx(const char* label_id, const double* xs, const double* ys, const int count, const int x_bins, const int y_bins, c::ImPlotRect range, const c::ImPlotHistogramFlags flags)
{
    return ::ImPlot::PlotHistogram2D(label_id, xs, ys, count, x_bins, y_bins, *reinterpret_cast<::ImPlotRect*>(&range), flags);
}

CIMGUI_API void ImPlot_PlotDigital(const char* label_id, const double* xs, const double* ys, const int count, const c::ImPlotDigitalFlags flags)
{
    ::ImPlot::PlotDigital(label_id, xs, ys, count, flags);
}

CIMGUI_API void ImPlot_PlotDigitalEx(const char* label_id, const double* xs, const double* ys, const int count, const c::ImPlotDigitalFlags flags, const int offset, const int stride)
{
    ::ImPlot::PlotDigital(label_id, xs, ys, count, flags, offset, stride);
}

CIMGUI_API void ImPlot_PlotDigitalG(const char* label_id, const c::ImPlotGetter getter, void* data, const int count, const c::ImPlotDigitalFlags flags)
{
    ::ImPlot::PlotDigitalG(label_id, reinterpret_cast<::ImPlotGetter>(getter), data, count, flags);
}

#ifdef IMGUI_HAS_TEXTURES

CIMGUI_API void ImPlot_PlotImage(const char* label_id, c::ImTextureRef tex_ref, c::ImPlotPoint bounds_min, c::ImPlotPoint bounds_max)
{
    ::ImPlot::PlotImage(label_id, tex_ref, reinterpret_cast<const ::ImPlotPoint&>(bounds_min), reinterpret_cast<const ::ImPlotPoint&>(bounds_max));
}

CIMGUI_API void ImPlot_PlotImageEx(const char* label_id, c::ImTextureRef tex_ref, c::ImPlotPoint bounds_min, c::ImPlotPoint bounds_max, c::ImVec2 uv0, c::ImVec2 uv1, c::ImVec4 tint_col, c::ImPlotImageFlags flags)
{
    ::ImPlot::PlotImage(label_id, tex_ref, reinterpret_cast<const ::ImPlotPoint&>(bounds_min), reinterpret_cast<const ::ImPlotPoint&>(bounds_max), reinterpret_cast<const ::ImVec2&>(uv0), reinterpret_cast<const ::ImVec2&>(uv1), reinterpret_cast<const ::ImVec4&>(tint_col), flags);
}

#endif // #ifdef IMGUI_HAS_TEXTURES

#ifndef IMGUI_HAS_TEXTURES

CIMGUI_API void ImPlot_PlotImage(const char* label_id, const c::ImTextureID tex_ref, const c::ImPlotPoint bounds_min, const c::ImPlotPoint bounds_max)
{
    ::ImPlot::PlotImage(label_id, tex_ref, reinterpret_cast<const ::ImPlotPoint&>(bounds_min), reinterpret_cast<const ::ImPlotPoint&>(bounds_max));
}

CIMGUI_API void ImPlot_PlotImageEx(const char* label_id, const c::ImTextureID tex_ref, const c::ImPlotPoint bounds_min, const c::ImPlotPoint bounds_max, const c::ImVec2 uv0, const c::ImVec2 uv1, const c::ImVec4 tint_col, const c::ImPlotImageFlags flags)
{
    ::ImPlot::PlotImage(label_id, tex_ref, reinterpret_cast<const ::ImPlotPoint&>(bounds_min), reinterpret_cast<const ::ImPlotPoint&>(bounds_max), reinterpret_cast<const ::ImVec2&>(uv0), reinterpret_cast<const ::ImVec2&>(uv1), reinterpret_cast<const ::ImVec4&>(tint_col), flags);
}

#endif // #ifndef IMGUI_HAS_TEXTURES

CIMGUI_API void ImPlot_PlotText(const char* text, const double x, const double y)
{
    ::ImPlot::PlotText(text, x, y);
}

CIMGUI_API void ImPlot_PlotTextEx(const char* text, const double x, const double y, const c::ImVec2 pix_offset, const c::ImPlotTextFlags flags)
{
    ::ImPlot::PlotText(text, x, y, reinterpret_cast<const ::ImVec2&>(pix_offset), flags);
}

CIMGUI_API void ImPlot_PlotDummy(const char* label_id, const c::ImPlotDummyFlags flags)
{
    ::ImPlot::PlotDummy(label_id, flags);
}

CIMGUI_API bool ImPlot_DragPoint(const int id, double* x, double* y, const c::ImVec4 col)
{
    return ::ImPlot::DragPoint(id, x, y, reinterpret_cast<const ::ImVec4&>(col));
}

CIMGUI_API bool ImPlot_DragPointEx(const int id, double* x, double* y, const c::ImVec4 col, const float size, const c::ImPlotDragToolFlags flags, bool* out_clicked, bool* out_hovered, bool* held)
{
    return ::ImPlot::DragPoint(id, x, y, reinterpret_cast<const ::ImVec4&>(col), size, flags, out_clicked, out_hovered, held);
}

CIMGUI_API bool ImPlot_DragLineX(const int id, double* x, const c::ImVec4 col)
{
    return ::ImPlot::DragLineX(id, x, reinterpret_cast<const ::ImVec4&>(col));
}

CIMGUI_API bool ImPlot_DragLineXEx(const int id, double* x, const c::ImVec4 col, const float thickness, const c::ImPlotDragToolFlags flags, bool* out_clicked, bool* out_hovered, bool* held)
{
    return ::ImPlot::DragLineX(id, x, reinterpret_cast<const ::ImVec4&>(col), thickness, flags, out_clicked, out_hovered, held);
}

CIMGUI_API bool ImPlot_DragLineY(const int id, double* y, const c::ImVec4 col)
{
    return ::ImPlot::DragLineY(id, y, reinterpret_cast<const ::ImVec4&>(col));
}

CIMGUI_API bool ImPlot_DragLineYEx(const int id, double* y, const c::ImVec4 col, const float thickness, const c::ImPlotDragToolFlags flags, bool* out_clicked, bool* out_hovered, bool* held)
{
    return ::ImPlot::DragLineY(id, y, reinterpret_cast<const ::ImVec4&>(col), thickness, flags, out_clicked, out_hovered, held);
}

CIMGUI_API bool ImPlot_DragRect(const int id, double* x1, double* y1, double* x2, double* y2, const c::ImVec4 col, const c::ImPlotDragToolFlags flags)
{
    return ::ImPlot::DragRect(id, x1, y1, x2, y2, reinterpret_cast<const ::ImVec4&>(col), flags);
}

CIMGUI_API bool ImPlot_DragRectEx(const int id, double* x1, double* y1, double* x2, double* y2, const c::ImVec4 col, const c::ImPlotDragToolFlags flags, bool* out_clicked, bool* out_hovered, bool* held)
{
    return ::ImPlot::DragRect(id, x1, y1, x2, y2, reinterpret_cast<const ::ImVec4&>(col), flags, out_clicked, out_hovered, held);
}

CIMGUI_API void ImPlot_Annotation(const double x, const double y, const c::ImVec4 col, const c::ImVec2 pix_offset, const bool clamp)
{
    ::ImPlot::Annotation(x, y, reinterpret_cast<const ::ImVec4&>(col), reinterpret_cast<const ::ImVec2&>(pix_offset), clamp);
}

CIMGUI_API void ImPlot_AnnotationEx(const double x, const double y, const c::ImVec4 col, const c::ImVec2 pix_offset, const bool clamp, const bool round)
{
    ::ImPlot::Annotation(x, y, reinterpret_cast<const ::ImVec4&>(col), reinterpret_cast<const ::ImVec2&>(pix_offset), clamp, round);
}

CIMGUI_API void ImPlot_AnnotationStr(const double x, const double y, const c::ImVec4 col, const c::ImVec2 pix_offset, const bool clamp, const char* fmt, ...)
{
    va_list args;
    va_start(args, fmt);
    ::ImPlot::AnnotationV(x, y, reinterpret_cast<const ::ImVec4&>(col), reinterpret_cast<const ::ImVec2&>(pix_offset), clamp, fmt, args);
    va_end(args);
}

CIMGUI_API void ImPlot_AnnotationV(const double x, const double y, const c::ImVec4 col, const c::ImVec2 pix_offset, const bool clamp, const char* fmt, va_list args)
{
    ::ImPlot::AnnotationV(x, y, reinterpret_cast<const ::ImVec4&>(col), reinterpret_cast<const ::ImVec2&>(pix_offset), clamp, fmt, args);
}

CIMGUI_API void ImPlot_TagX(const double x, const c::ImVec4 col)
{
    ::ImPlot::TagX(x, reinterpret_cast<const ::ImVec4&>(col));
}

CIMGUI_API void ImPlot_TagXEx(const double x, const c::ImVec4 col, const bool round)
{
    ::ImPlot::TagX(x, reinterpret_cast<const ::ImVec4&>(col), round);
}

CIMGUI_API void ImPlot_TagXStr(const double x, const c::ImVec4 col, const char* fmt, ...)
{
    va_list args;
    va_start(args, fmt);
    ::ImPlot::TagXV(x, reinterpret_cast<const ::ImVec4&>(col), fmt, args);
    va_end(args);
}

CIMGUI_API void ImPlot_TagXV(const double x, const c::ImVec4 col, const char* fmt, va_list args)
{
    ::ImPlot::TagXV(x, reinterpret_cast<const ::ImVec4&>(col), fmt, args);
}

CIMGUI_API void ImPlot_TagY(const double y, const c::ImVec4 col)
{
    ::ImPlot::TagY(y, reinterpret_cast<const ::ImVec4&>(col));
}

CIMGUI_API void ImPlot_TagYEx(const double y, const c::ImVec4 col, const bool round)
{
    ::ImPlot::TagY(y, reinterpret_cast<const ::ImVec4&>(col), round);
}

CIMGUI_API void ImPlot_TagYStr(const double y, const c::ImVec4 col, const char* fmt, ...)
{
    va_list args;
    va_start(args, fmt);
    ::ImPlot::TagYV(y, reinterpret_cast<const ::ImVec4&>(col), fmt, args);
    va_end(args);
}

CIMGUI_API void ImPlot_TagYV(const double y, const c::ImVec4 col, const char* fmt, va_list args)
{
    ::ImPlot::TagYV(y, reinterpret_cast<const ::ImVec4&>(col), fmt, args);
}

CIMGUI_API void ImPlot_SetAxis(const c::ImAxis axis)
{
    ::ImPlot::SetAxis(axis);
}

CIMGUI_API void ImPlot_SetAxes(const c::ImAxis x_axis, const c::ImAxis y_axis)
{
    ::ImPlot::SetAxes(x_axis, y_axis);
}

CIMGUI_API c::ImPlotPoint ImPlot_PixelsToPlot(const c::ImVec2 pix)
{
    TMPCAST(::ImPlot::PixelsToPlot(reinterpret_cast<const ::ImVec2&>(pix)), c::ImPlotPoint);
}

CIMGUI_API c::ImPlotPoint ImPlot_PixelsToPlotEx(const c::ImVec2 pix, const c::ImAxis x_axis, const c::ImAxis y_axis)
{
    TMPCAST(::ImPlot::PixelsToPlot(reinterpret_cast<const ::ImVec2&>(pix), x_axis, y_axis), c::ImPlotPoint);
}

CIMGUI_API c::ImPlotPoint ImPlot_PixelsToPlotFloat(const float x, const float y)
{
    TMPCAST(::ImPlot::PixelsToPlot(x, y), c::ImPlotPoint);
}

CIMGUI_API c::ImPlotPoint ImPlot_PixelsToPlotFloatEx(const float x, const float y, const c::ImAxis x_axis, const c::ImAxis y_axis)
{
    TMPCAST(::ImPlot::PixelsToPlot(x, y, x_axis, y_axis), c::ImPlotPoint);
}

CIMGUI_API c::ImVec2 ImPlot_PlotToPixels(const c::ImPlotPoint plt)
{
    TMPCAST(::ImPlot::PlotToPixels(reinterpret_cast<const ::ImPlotPoint&>(plt)), c::ImVec2);
}

CIMGUI_API c::ImVec2 ImPlot_PlotToPixelsEx(const c::ImPlotPoint plt, const c::ImAxis x_axis, const c::ImAxis y_axis)
{
    TMPCAST(::ImPlot::PlotToPixels(reinterpret_cast<const ::ImPlotPoint&>(plt), x_axis, y_axis), c::ImVec2);
}

CIMGUI_API c::ImVec2 ImPlot_PlotToPixelsDouble(const double x, const double y)
{
    TMPCAST(::ImPlot::PlotToPixels(x, y), c::ImVec2);
}

CIMGUI_API c::ImVec2 ImPlot_PlotToPixelsDoubleEx(const double x, const double y, const c::ImAxis x_axis, const c::ImAxis y_axis)
{
    TMPCAST(::ImPlot::PlotToPixels(x, y, x_axis, y_axis), c::ImVec2);
}

CIMGUI_API c::ImVec2 ImPlot_GetPlotPos()
{
    TMPCAST(::ImPlot::GetPlotPos(), c::ImVec2);
}

CIMGUI_API c::ImVec2 ImPlot_GetPlotSize()
{
    TMPCAST(::ImPlot::GetPlotSize(), c::ImVec2);
}

CIMGUI_API c::ImPlotPoint ImPlot_GetPlotMousePos()
{
    TMPCAST(::ImPlot::GetPlotMousePos(), c::ImPlotPoint);
}

CIMGUI_API c::ImPlotPoint ImPlot_GetPlotMousePosEx(const c::ImAxis x_axis, const c::ImAxis y_axis)
{
    TMPCAST(::ImPlot::GetPlotMousePos(x_axis, y_axis), c::ImPlotPoint);
}

CIMGUI_API c::ImPlotRect ImPlot_GetPlotLimits()
{
    TMPCAST(::ImPlot::GetPlotLimits(), c::ImPlotRect);
}

CIMGUI_API c::ImPlotRect ImPlot_GetPlotLimitsEx(const c::ImAxis x_axis, const c::ImAxis y_axis)
{
    TMPCAST(::ImPlot::GetPlotLimits(x_axis, y_axis), c::ImPlotRect);
}

CIMGUI_API bool ImPlot_IsPlotHovered()
{
    return ::ImPlot::IsPlotHovered();
}

CIMGUI_API bool ImPlot_IsAxisHovered(const c::ImAxis axis)
{
    return ::ImPlot::IsAxisHovered(axis);
}

CIMGUI_API bool ImPlot_IsSubplotsHovered()
{
    return ::ImPlot::IsSubplotsHovered();
}

CIMGUI_API bool       ImPlot_IsPlotSelected()
{
    return ::ImPlot::IsPlotSelected();
}

CIMGUI_API c::ImPlotRect ImPlot_GetPlotSelection()
{
    TMPCAST(::ImPlot::GetPlotSelection(), c::ImPlotRect);
}

CIMGUI_API c::ImPlotRect ImPlot_GetPlotSelectionEx(const c::ImAxis x_axis, const c::ImAxis y_axis)
{
    TMPCAST(::ImPlot::GetPlotSelection(x_axis, y_axis), c::ImPlotRect);
}

CIMGUI_API void       ImPlot_CancelPlotSelection()
{
    ::ImPlot::CancelPlotSelection();
}

CIMGUI_API void ImPlot_HideNextItem()
{
    ::ImPlot::HideNextItem();
}

CIMGUI_API void ImPlot_HideNextItemEx(const bool hidden, const c::ImPlotCond cond)
{
    ::ImPlot::HideNextItem(hidden, cond);
}

CIMGUI_API bool ImPlot_BeginAlignedPlots(const char* group_id)
{
    return ::ImPlot::BeginAlignedPlots(group_id);
}

CIMGUI_API bool ImPlot_BeginAlignedPlotsEx(const char* group_id, const bool vertical)
{
    return ::ImPlot::BeginAlignedPlots(group_id, vertical);
}

CIMGUI_API void ImPlot_EndAlignedPlots()
{
    ::ImPlot::EndAlignedPlots();
}

CIMGUI_API bool ImPlot_BeginLegendPopup(const char* label_id)
{
    return ::ImPlot::BeginLegendPopup(label_id);
}

CIMGUI_API bool ImPlot_BeginLegendPopupEx(const char* label_id, const c::ImGuiMouseButton mouse_button)
{
    return ::ImPlot::BeginLegendPopup(label_id, mouse_button);
}

CIMGUI_API void ImPlot_EndLegendPopup()
{
    ::ImPlot::EndLegendPopup();
}

CIMGUI_API bool ImPlot_IsLegendEntryHovered(const char* label_id)
{
    return ::ImPlot::IsLegendEntryHovered(label_id);
}

CIMGUI_API bool ImPlot_BeginDragDropTargetPlot()
{
    return ::ImPlot::BeginDragDropTargetPlot();
}

CIMGUI_API bool ImPlot_BeginDragDropTargetAxis(const c::ImAxis axis)
{
    return ::ImPlot::BeginDragDropTargetAxis(axis);
}

CIMGUI_API bool ImPlot_BeginDragDropTargetLegend()
{
    return ::ImPlot::BeginDragDropTargetLegend();
}

CIMGUI_API void ImPlot_EndDragDropTarget()
{
    ::ImPlot::EndDragDropTarget();
}

CIMGUI_API bool ImPlot_BeginDragDropSourcePlot(const c::ImGuiDragDropFlags flags)
{
    return ::ImPlot::BeginDragDropSourcePlot(flags);
}

CIMGUI_API bool ImPlot_BeginDragDropSourceAxis(const c::ImAxis axis, const c::ImGuiDragDropFlags flags)
{
    return ::ImPlot::BeginDragDropSourceAxis(axis, flags);
}

CIMGUI_API bool ImPlot_BeginDragDropSourceItem(const char* label_id, const c::ImGuiDragDropFlags flags)
{
    return ::ImPlot::BeginDragDropSourceItem(label_id, flags);
}

CIMGUI_API void ImPlot_EndDragDropSource()
{
    ::ImPlot::EndDragDropSource();
}

CIMGUI_API c::ImPlotStyle* ImPlot_GetStyle()
{
    return reinterpret_cast<c::ImPlotStyle*>(&::ImPlot::GetStyle());
}

CIMGUI_API void ImPlot_StyleColorsAuto()
{
    ::ImPlot::StyleColorsAuto();
}

CIMGUI_API void ImPlot_StyleColorsAutoEx(c::ImPlotStyle* dst)
{
    ::ImPlot::StyleColorsAuto(reinterpret_cast<::ImPlotStyle*>(dst));
}

CIMGUI_API void ImPlot_StyleColorsClassic()
{
    ::ImPlot::StyleColorsClassic();
}

CIMGUI_API void ImPlot_StyleColorsClassicEx(c::ImPlotStyle* dst)
{
    ::ImPlot::StyleColorsClassic(reinterpret_cast<::ImPlotStyle*>(dst));
}

CIMGUI_API void ImPlot_StyleColorsDark()
{
    ::ImPlot::StyleColorsDark();
}

CIMGUI_API void ImPlot_StyleColorsDarkEx(c::ImPlotStyle* dst)
{
    ::ImPlot::StyleColorsDark(reinterpret_cast<::ImPlotStyle*>(dst));
}

CIMGUI_API void ImPlot_StyleColorsLight()
{
    ::ImPlot::StyleColorsLight();
}

CIMGUI_API void ImPlot_StyleColorsLightEx(c::ImPlotStyle* dst)
{
    ::ImPlot::StyleColorsLight(reinterpret_cast<::ImPlotStyle*>(dst));
}

CIMGUI_API void ImPlot_PushStyleColor(const c::ImPlotCol idx, const c::ImU32 col)
{
    ::ImPlot::PushStyleColor(idx, col);
}

CIMGUI_API void ImPlot_PushStyleColorImVec4(const c::ImPlotCol idx, const c::ImVec4 col)
{
    ::ImPlot::PushStyleColor(idx, reinterpret_cast<const ::ImVec4&>(col));
}

CIMGUI_API void ImPlot_PopStyleColor()
{
    ::ImPlot::PopStyleColor();
}

CIMGUI_API void ImPlot_PopStyleColorEx(const int count)
{
    ::ImPlot::PopStyleColor(count);
}

CIMGUI_API void ImPlot_PushStyleVar(const c::ImPlotStyleVar idx, const float val)
{
    ::ImPlot::PushStyleVar(idx, val);
}

CIMGUI_API void ImPlot_PushStyleVarInt(const c::ImPlotStyleVar idx, const int val)
{
    ::ImPlot::PushStyleVar(idx, val);
}

CIMGUI_API void ImPlot_PushStyleVarImVec2(const c::ImPlotStyleVar idx, const c::ImVec2 val)
{
    ::ImPlot::PushStyleVar(idx, reinterpret_cast<const ::ImVec2&>(val));
}

CIMGUI_API void ImPlot_PopStyleVar()
{
    ::ImPlot::PopStyleVar();
}

CIMGUI_API void ImPlot_PopStyleVarEx(const int count)
{
    ::ImPlot::PopStyleVar(count);
}

CIMGUI_API void ImPlot_SetNextLineStyle()
{
    ::ImPlot::SetNextLineStyle();
}

CIMGUI_API void ImPlot_SetNextLineStyleEx(const c::ImVec4 col, const float weight)
{
    ::ImPlot::SetNextLineStyle(reinterpret_cast<const ::ImVec4&>(col), weight);
}

CIMGUI_API void ImPlot_SetNextFillStyle()
{
    ::ImPlot::SetNextFillStyle();
}

CIMGUI_API void ImPlot_SetNextFillStyleEx(const c::ImVec4 col, const float alpha_mod)
{
    ::ImPlot::SetNextFillStyle(reinterpret_cast<const ::ImVec4&>(col), alpha_mod);
}

CIMGUI_API void ImPlot_SetNextMarkerStyle()
{
    ::ImPlot::SetNextMarkerStyle();
}

CIMGUI_API void ImPlot_SetNextMarkerStyleEx(const c::ImPlotMarker marker, const float size, const c::ImVec4 fill, const float weight, const c::ImVec4 outline)
{
    ::ImPlot::SetNextMarkerStyle(marker, size, reinterpret_cast<const ::ImVec4&>(fill), weight, reinterpret_cast<const ::ImVec4&>(outline));
}

CIMGUI_API void ImPlot_SetNextErrorBarStyle()
{
    ::ImPlot::SetNextErrorBarStyle();
}

CIMGUI_API void ImPlot_SetNextErrorBarStyleEx(const c::ImVec4 col, const float size, const float weight)
{
    ::ImPlot::SetNextErrorBarStyle(reinterpret_cast<const ::ImVec4&>(col), size, weight);
}

CIMGUI_API c::ImVec4 ImPlot_GetLastItemColor()
{
    TMPCAST(::ImPlot::GetLastItemColor(), c::ImVec4);
}

CIMGUI_API const char* ImPlot_GetStyleColorName(const c::ImPlotCol idx)
{
    return ::ImPlot::GetStyleColorName(idx);
}

CIMGUI_API const char* ImPlot_GetMarkerName(const c::ImPlotMarker idx)
{
    return ::ImPlot::GetMarkerName(idx);
}

CIMGUI_API c::ImPlotColormap ImPlot_AddColormap(const char* name, const c::ImVec4* cols, const int size)
{
    TMPCAST(::ImPlot::AddColormap(name, FCAST(const ::ImVec4*, cols), size), ImPlotColormap);
}

CIMGUI_API c::ImPlotColormap ImPlot_AddColormapEx(const char* name, const c::ImVec4* cols, const int size, const bool qual)
{
    return ::ImPlot::AddColormap(name, FCAST(const ::ImVec4*, cols), size, qual);
}

CIMGUI_API c::ImPlotColormap ImPlot_AddColormapImU32Ptr(const char* name, const c::ImU32* cols, const int size)
{
    return ::ImPlot::AddColormap(name, cols, size);
}

CIMGUI_API c::ImPlotColormap ImPlot_AddColormapImU32PtrEx(const char* name, const c::ImU32* cols, const int size, const bool qual)
{
    return ::ImPlot::AddColormap(name, cols, size, qual);
}

CIMGUI_API int            ImPlot_GetColormapCount()
{
    return ::ImPlot::GetColormapCount();
}

CIMGUI_API const char*    ImPlot_GetColormapName(const c::ImPlotColormap cmap)
{
    return ::ImPlot::GetColormapName(cmap);
}

CIMGUI_API c::ImPlotColormap ImPlot_GetColormapIndex(const char* name)
{
    return ::ImPlot::GetColormapIndex(name);
}

CIMGUI_API void ImPlot_PushColormap(const c::ImPlotColormap cmap)
{
    ::ImPlot::PushColormap(cmap);
}

CIMGUI_API void ImPlot_PushColormapStr(const char* name)
{
    ::ImPlot::PushColormap(name);
}

CIMGUI_API void ImPlot_PopColormap()
{
    ::ImPlot::PopColormap();
}

CIMGUI_API void ImPlot_PopColormapEx(const int count)
{
    ::ImPlot::PopColormap(count);
}

CIMGUI_API c::ImVec4 ImPlot_NextColormapColor()
{
    TMPCAST(::ImPlot::NextColormapColor(), c::ImVec4);
}

CIMGUI_API int    ImPlot_GetColormapSize()
{
    return ::ImPlot::GetColormapSize();
}

CIMGUI_API int    ImPlot_GetColormapSizeEx(const c::ImPlotColormap cmap)
{
    return ::ImPlot::GetColormapSize(cmap);
}

CIMGUI_API c::ImVec4 ImPlot_GetColormapColor(const int idx)
{
    TMPCAST(::ImPlot::GetColormapColor(idx), c::ImVec4);
}

CIMGUI_API c::ImVec4 ImPlot_GetColormapColorEx(const int idx, const c::ImPlotColormap cmap)
{
    TMPCAST(::ImPlot::GetColormapColor(idx, cmap), c::ImVec4);
}

CIMGUI_API c::ImVec4 ImPlot_SampleColormap(const float t)
{
    TMPCAST(::ImPlot::SampleColormap(t), c::ImVec4);
}

CIMGUI_API c::ImVec4 ImPlot_SampleColormapEx(const float t, const c::ImPlotColormap cmap)
{
    TMPCAST(::ImPlot::SampleColormap(t, cmap), c::ImVec4);
}

CIMGUI_API void ImPlot_ColormapScale(const char* label, const double scale_min, const double scale_max)
{
    ::ImPlot::ColormapScale(label, scale_min, scale_max);
}

CIMGUI_API void ImPlot_ColormapScaleEx(const char* label, const double scale_min, const double scale_max, const c::ImVec2 size, const char* format, const c::ImPlotColormapScaleFlags flags, const c::ImPlotColormap cmap)
{
    ::ImPlot::ColormapScale(label, scale_min, scale_max, reinterpret_cast<const ::ImVec2&>(size), format, flags, cmap);
}

CIMGUI_API bool ImPlot_ColormapSlider(const char* label, float* t)
{
    return ::ImPlot::ColormapSlider(label, t);
}

CIMGUI_API bool ImPlot_ColormapSliderEx(const char* label, float* t, c::ImVec4* out, const char* format, const c::ImPlotColormap cmap)
{
    return ::ImPlot::ColormapSlider(label, t, reinterpret_cast<::ImVec4*>(out), format, cmap);
}

CIMGUI_API bool ImPlot_ColormapButton(const char* label)
{
    return ::ImPlot::ColormapButton(label);
}

CIMGUI_API bool ImPlot_ColormapButtonEx(const char* label, const c::ImVec2 size, const c::ImPlotColormap cmap)
{
    return ::ImPlot::ColormapButton(label, reinterpret_cast<const ::ImVec2&>(size), cmap);
}

CIMGUI_API void ImPlot_BustColorCache()
{
    ::ImPlot::BustColorCache();
}

CIMGUI_API void ImPlot_BustColorCacheEx(const char* plot_title_id)
{
    ::ImPlot::BustColorCache(plot_title_id);
}

CIMGUI_API c::ImPlotInputMap* ImPlot_GetInputMap()
{
    return reinterpret_cast<c::ImPlotInputMap*>(&::ImPlot::GetInputMap());
}

CIMGUI_API void ImPlot_MapInputDefault()
{
    ::ImPlot::MapInputDefault();
}

CIMGUI_API void ImPlot_MapInputDefaultEx(c::ImPlotInputMap* dst)
{
    ::ImPlot::MapInputDefault(reinterpret_cast<::ImPlotInputMap*>(dst));
}

CIMGUI_API void ImPlot_MapInputReverse()
{
    ::ImPlot::MapInputReverse();
}

CIMGUI_API void ImPlot_MapInputReverseEx(c::ImPlotInputMap* dst)
{
    ::ImPlot::MapInputReverse(reinterpret_cast <::ImPlotInputMap*>(dst));
}

CIMGUI_API void ImPlot_ItemIcon(const c::ImVec4 col)
{
    ::ImPlot::ItemIcon(reinterpret_cast<const ::ImVec4&>(col));
}

CIMGUI_API void ImPlot_ItemIconImU32(const c::ImU32 col)
{
    ::ImPlot::ItemIcon(col);
}

CIMGUI_API void ImPlot_ColormapIcon(const c::ImPlotColormap cmap)
{
    ::ImPlot::ColormapIcon(cmap);
}

CIMGUI_API c::ImDrawList* ImPlot_GetPlotDrawList()
{
    return reinterpret_cast<c::ImDrawList*>(::ImPlot::GetPlotDrawList());
}

CIMGUI_API void        ImPlot_PushPlotClipRect()
{
    ::ImPlot::PushPlotClipRect();
}

CIMGUI_API void        ImPlot_PushPlotClipRectEx(const float expand)
{
    ::ImPlot::PushPlotClipRect(expand);
}

CIMGUI_API void        ImPlot_PopPlotClipRect()
{
    ::ImPlot::PopPlotClipRect();
}

CIMGUI_API bool ImPlot_ShowStyleSelector(const char* label)
{
    return ::ImPlot::ShowStyleSelector(label);
}

CIMGUI_API bool ImPlot_ShowColormapSelector(const char* label)
{
    return ::ImPlot::ShowColormapSelector(label);
}

CIMGUI_API bool ImPlot_ShowInputMapSelector(const char* label)
{
    return ::ImPlot::ShowInputMapSelector(label);
}

CIMGUI_API void ImPlot_ShowStyleEditor()
{
    ::ImPlot::ShowStyleEditor();
}

CIMGUI_API void ImPlot_ShowStyleEditorEx(c::ImPlotStyle* ref)
{
    ::ImPlot::ShowStyleEditor(reinterpret_cast<::ImPlotStyle*>(ref));
}

CIMGUI_API void ImPlot_ShowUserGuide()
{
    ::ImPlot::ShowUserGuide();
}

CIMGUI_API void ImPlot_ShowMetricsWindow()
{
    ::ImPlot::ShowMetricsWindow();
}

CIMGUI_API void ImPlot_ShowMetricsWindowEx(bool* p_popen)
{
    ::ImPlot::ShowMetricsWindow(p_popen);
}

CIMGUI_API void ImPlot_ShowDemoWindow()
{
    ::ImPlot::ShowDemoWindow();
}

CIMGUI_API void ImPlot_ShowDemoWindowEx(bool* p_open)
{
    ::ImPlot::ShowDemoWindow(p_open);
}

}
#endif // #ifndef IMGUI_DISABLE
#endif