#pragma once
#ifdef __has_include
#if __has_include(<imspinner.h>)
#include "cimgui_extra_common.h"

#ifdef __cplusplus
extern "C"
{
#endif

#define IMSPINNER_PI 3.14159265358979323846f
#define IMSPINNER_PI_2 (IMSPINNER_PI * 2.f)

    typedef CImXVec4(*ImSpinner_LeafColor)(int);

    MLS_PUBLIC_API void ImSpinner_SpinnerAngTriple(             const char* label, float        radius1,    float radius2,          float           radius3,        float           thickness,      const CImXVec4* c1,         const CImXVec4* c2,         const CImXVec4* c3,     float   speed,  float   angle);
    MLS_PUBLIC_API void ImSpinner_SpinnerAngTwin(               const char* label, float        radius1,    float radius2,          float           thickness,      const CImXVec4* color,          const CImXVec4* bg,         float           speed,      float           angle,  size_t  arcs,   int     mode );

    MLS_PUBLIC_API void ImSpinner_SpinnerTwinBall(              const char* label, float        radius1,    float radius2,          float           thickness,      float           b_thickness,    const CImXVec4* ball,       const CImXVec4* bg,         float           speed,  size_t  balls   );
    MLS_PUBLIC_API void ImSpinner_SpinnerTwinHboDots(           const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           minfade,        float           ryk,        float           speed,      size_t          dots,   float   delta   );
    MLS_PUBLIC_API void ImSpinner_SpinnerRainbow(               const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          float           ang_min,    float           ang_max,    int             arcs,   int     mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerRainbowMix(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          float           ang_min,    float           ang_max,    int             arcs,   int     mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerAng8(                  const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed,      float           angle,      int             mode,   float   rkoef   );
    MLS_PUBLIC_API void ImSpinner_SpinnerDots(                  const char* label, float*       nextdot,    float radius,           float           thickness,      const CImXVec4* color,          float           speed,      size_t          dots2,      float           minth,  int     mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerVDots(                 const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bgcolor,        float           speed,      size_t          dots2,      size_t          mdots,  int     mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerTwinAng(               const char* label, float        radius1,    float radius2,          float           thickness,      const CImXVec4* color1,         const CImXVec4* color2,     float           speed,      float           angle,  int     mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerTwinAng180(            const char* label, float        radius1,    float radius2,          float           thickness,      const CImXVec4* color1,         const CImXVec4* color2,     float           speed,      float           angle,  int     mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerTwinAng360(            const char* label, float        radius1,    float radius2,          float           thickness,      const CImXVec4* color1,         const CImXVec4* color2,     float           speed1,     float           speed2, int     mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerIngYang(               const char* label, float        radius,     float thickness,        bool            reverse,        float           yang_detlta_r,  const CImXVec4* colorI,     const CImXVec4* colorY,     float           speed,  float   angle   );

    MLS_PUBLIC_API void ImSpinner_SpinnerCircleDrop(            const char* label, float        radius,     float thickness,        float           thickness_drop, const CImXVec4* color,          const CImXVec4* bg,         float           speed,      float           angle   );
    MLS_PUBLIC_API void ImSpinner_SpinnerAngMix(                const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          float           angle,      int             arcs,       int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerAng(                   const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed,      float           angle,      int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerPulsar(                const char* label, float        radius,     float thickness,        const CImXVec4* bg,             float           speed,          bool            sequence,   float           angle,      int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerIncScaleDots(          const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          dots,       float           angle,      int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerRotateSegments(        const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          arcs,       size_t          layers,     int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerPointsArcBounce(       const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          points,     int             circles,    float           rspeed  );
    MLS_PUBLIC_API void ImSpinner_SpinnerWifiIndicator(         const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed,      float           cangle,     int             dots    );
    MLS_PUBLIC_API void ImSpinner_SpinnerPatternEclipse(        const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             elipses,    float           delta_a,    float           delta_y );
    MLS_PUBLIC_API void ImSpinner_SpinnerHboDots(               const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           minfade,        float           ryk,        float           speed,      size_t          dots    );
    MLS_PUBLIC_API void ImSpinner_SpinnerThreeDotsStar(         const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           minfade,        float           ryk,        float           speed,      float           delta   );
    MLS_PUBLIC_API void ImSpinner_SpinnerDnaDots(               const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             lt,         float           delta,      bool            mode    );
    MLS_PUBLIC_API void ImSpinner_Spinner3SmuggleDots(          const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             lt,         float           delta,      bool            mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerSplineAng(             const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed,      float           angle,      int             mode    );

    MLS_PUBLIC_API void ImSpinner_SpinnerTwinPulsar(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             rings,      int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerBounceDots(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          dots,       int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerFadeDots(              const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             lt,         int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerRotateDots(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             dots,       int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerRainbowCircle(         const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          arcs,       float           mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerRotateGooeyBalls(      const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             balls,      int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerBounceBall(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             dots,       bool            shadow      );
    MLS_PUBLIC_API void ImSpinner_SpinnerPulsarBall(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          bool            shadow,     int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerSomeScaleDots(         const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          dots,       int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerLoadingRing(           const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed,      int             segments    );
    MLS_PUBLIC_API void ImSpinner_SpinnerRotateShapes(          const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             shapes,     int             pnt         );
    MLS_PUBLIC_API void ImSpinner_SpinnerDotsToPoints(          const char* label, float        radius,     float thickness,        float           offset_k,       const CImXVec4* color,          float           speed,      size_t          dots        );
    MLS_PUBLIC_API void ImSpinner_SpinnerDotsToBar(             const char* label, float        radius,     float thickness,        float           offset_k,       const CImXVec4* color,          float           speed,      size_t          dots        );
    MLS_PUBLIC_API void ImSpinner_SpinnerTopup(                 const char* label, float        radius1,    float radius2,          const CImXVec4* color,          const CImXVec4* fg,             const CImXVec4* bg,         float           speed       );
    MLS_PUBLIC_API void ImSpinner_SpinnerBarsRotateFade(        const char* label, float        rmin,       float rmax,             float           thickness,      const CImXVec4* color,          float           speed,      size_t          bars        );
    MLS_PUBLIC_API void ImSpinner_SpinnerFilledArcRing(         const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed,      size_t          arcs        );
    MLS_PUBLIC_API void ImSpinner_SpinnerArcRotation(           const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          arcs,       int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerArcFade(               const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          arcs,       int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerRotatedAtom(           const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             elipses,    int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerRainbowBalls(          const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             balls,      int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerBarChartSine(          const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             bars,       int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerBarChartRainbow(       const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             bars,       int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerSolarBalls(            const char* label, float        radius,     float thickness,        const CImXVec4* ball,           const CImXVec4* bg,             float           speed,      size_t          balls       );
    MLS_PUBLIC_API void ImSpinner_SpinnerSolarArcs(             const char* label, float        radius,     float thickness,        const CImXVec4* ball,           const CImXVec4* bg,             float           speed,      size_t          balls       );
    MLS_PUBLIC_API void ImSpinner_SpinnerTrianglesSelector(     const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed,      size_t          bars        );
    MLS_PUBLIC_API void ImSpinner_SpinnerRotateWheel(           const char* label, float        radius,     float thickness,        const CImXVec4* bg_color,       const CImXVec4* color,          float           speed,      size_t          pins2       );
    MLS_PUBLIC_API void ImSpinner_SpinnerFlowingGradient(       const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed,      float           angle       );
    MLS_PUBLIC_API void ImSpinner_SpinnerMoonLine(              const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed,      float           angle       );
    MLS_PUBLIC_API void ImSpinner_SpinnerFluidPoints(           const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          dots,       float           delta       );
    MLS_PUBLIC_API void ImSpinner_SpinnerCamera(                const char* label, float        radius,     float thickness,        ImSpinner_LeafColor* leaf_color,float           speed,          size_t          bars,       int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerTrianglesShift(        const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed,      size_t          bars        );
    MLS_PUBLIC_API void ImSpinner_SpinnerPointsShift(           const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed,      size_t          bars        );
    MLS_PUBLIC_API void ImSpinner_SpinnerCaleidoscope(          const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          arcs,       int             mode        );
    MLS_PUBLIC_API void ImSpinner_SpinnerModCircle(             const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           ang_min,        float           ang_max,    float           speed       );
    MLS_PUBLIC_API void ImSpinner_SpinnerRotateSegmentsPulsar(  const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          arcs,       size_t          layers      );

    MLS_PUBLIC_API void ImSpinner_SpinnerRotatingHeart(         const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          float           ang_min );
    MLS_PUBLIC_API void ImSpinner_SpinnerClock(                 const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerFilling(               const char* label, float        radius,     float thickness,        const CImXVec4* color1,         const CImXVec4* color2,         float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerFillingMem(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          CImXVec4*       colorbg,        float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerAsciiSymbolPoints(     const char* label, const char*  text,       float radius,           float           thickness,      const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerTextFading(            const char* label, const char*  text,       float radius,           float           fsize,          const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSevenSegments(         const char* label, const char*  text,       float radius,           float           thickness,      const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSinSquares(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerRotateTriangles(       const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             tris    );
    MLS_PUBLIC_API void ImSpinner_SpinnerSurroundedIndicator(   const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerLemniscate(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          float           angle   );
    MLS_PUBLIC_API void ImSpinner_SpinnerRotateGear(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          pins2   );
    MLS_PUBLIC_API void ImSpinner_SpinnerAtom(                  const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             elipses );
    MLS_PUBLIC_API void ImSpinner_SpinnerPatternRings(          const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             elipses );
    MLS_PUBLIC_API void ImSpinner_SpinnerPatternSphere(         const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             elipses );
    MLS_PUBLIC_API void ImSpinner_SpinnerRingSynchronous(       const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             elipses );
    MLS_PUBLIC_API void ImSpinner_SpinnerRingWatermarks(        const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             elipses );
    MLS_PUBLIC_API void ImSpinner_SpinnerRainbowShot(           const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             balls   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSpiral(                const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          arcs    );
    MLS_PUBLIC_API void ImSpinner_SpinnerFadePulsar(            const char* label, float        radius,     const CImXVec4* color,  float           speed,          int             rings,          int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerCircularLines(         const char* label, float        radius,     const CImXVec4* color,  float           speed,          int             lines,          int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerFilledArcFade(         const char* label, float        radius,     const CImXVec4* color,  float           speed,          size_t          arcs,           int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerZipDots(               const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          dots    );
    MLS_PUBLIC_API void ImSpinner_SpinnerWaveDots(              const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             lt      );
    MLS_PUBLIC_API void ImSpinner_SpinnerThreeDots(             const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             lt      );
    MLS_PUBLIC_API void ImSpinner_SpinnerFiveDots(              const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             lt      );
    MLS_PUBLIC_API void ImSpinner_Spinner4Caleidospcope(        const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             lt      );
    MLS_PUBLIC_API void ImSpinner_SpinnerMultiFadeDots(         const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             lt      );
    MLS_PUBLIC_API void ImSpinner_SpinnerScaleDots(             const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             lt      );
    MLS_PUBLIC_API void ImSpinner_SpinnerMovingDots(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          dots    );
    MLS_PUBLIC_API void ImSpinner_SpinnerOrionDots(             const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             arcs    );
    MLS_PUBLIC_API void ImSpinner_SpinnerGalaxyDots(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             arcs    );
    MLS_PUBLIC_API void ImSpinner_SpinnerIncDots(               const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          dots    );
    MLS_PUBLIC_API void ImSpinner_SpinnerIncFullDots(           const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          dots    );
    MLS_PUBLIC_API void ImSpinner_SpinnerFadeBars(              const char* label, float        w,          const CImXVec4* color,  float           speed,          size_t          bars,           bool            scale   );
    MLS_PUBLIC_API void ImSpinner_SpinnerFadeTris(              const char* label, float        radius,     const CImXVec4* color,  float           speed,          size_t          dim,            bool            scale   );
    MLS_PUBLIC_API void ImSpinner_SpinnerFilledArcColor(        const char* label, float        radius,     const CImXVec4* color,  const CImXVec4* bg,             float           speed,          size_t          arcs    );
    MLS_PUBLIC_API void ImSpinner_SpinnerDotsLoading(           const char* label, float        radius,     float thickness,        const CImXVec4* color,          const CImXVec4* bg,             float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerHerbertBalls(          const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             balls   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSolarScaleBalls(       const char* label, float        radius,     float thickness,        const CImXVec4* ball,           float           speed,          size_t          balls   );
    MLS_PUBLIC_API void ImSpinner_SpinnerMovingArcs(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          arcs    );
    MLS_PUBLIC_API void ImSpinner_SpinnerAngEclipse(            const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          float           angle   );
    MLS_PUBLIC_API void ImSpinner_SpinnerBarChartAdvSine(       const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerBarChartAdvSineFade(   const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerBlocks(                const char* label, float        radius,     float thickness,        const CImXVec4* bg,             const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerTwinBlocks(            const char* label, float        radius,     float thickness,        const CImXVec4* bg,             const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSquareRandomDots(      const char* label, float        radius,     float thickness,        const CImXVec4* bg,             const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerScaleBlocks(           const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerMoonDots(              const char* label, float        radius,     float thickness,        const CImXVec4* first,          const CImXVec4* second,         float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerArcPolarFade(          const char* label, float        radius,     const CImXVec4* color,  float           speed,          size_t          arcs,           int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerCircularPoints(        const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          int             lines   );
    MLS_PUBLIC_API void ImSpinner_SpinnerCurvedCircle(          const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed,          size_t          circles );

    MLS_PUBLIC_API void ImSpinner_SpinnerArcWedges(             const char* label, float        radius,     const CImXVec4* color,  float           speed,          size_t          arcs    );
    MLS_PUBLIC_API void ImSpinner_SpinnerGooeyBalls(            const char* label, float        radius,     const CImXVec4* color,  float           speed,          int             mode    );
    MLS_PUBLIC_API void ImSpinner_SpinnerDoubleFadePulsar(      const char* label, float        radius,     float thickness,        const CImXVec4* bg,             float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerBarsScaleMiddle(       const char* label, float        w,          const CImXVec4* color,  float           speed,          size_t          bars    );
    MLS_PUBLIC_API void ImSpinner_SpinnerHerbertBalls3D(        const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSimpleArcFade(         const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSquareStrokeFade(      const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSquareStrokeFill(      const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSquareStrokeLoading(   const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSquareLoading(         const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSquareSpins(           const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSpiralEye(             const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerScaleSquares(          const char* label, float        radius,     float thikness,         const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerFluid(                 const char* label, float        radius,     const CImXVec4* color,  float           speed,          int             bars    );
    MLS_PUBLIC_API void ImSpinner_SpinnerArcPolarRadius(        const char* label, float        radius,     const CImXVec4* color,  float           speed,          size_t          arcs    );
    MLS_PUBLIC_API void ImSpinner_SpinnerSineArcs(              const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed   );
    MLS_PUBLIC_API void ImSpinner_SpinnerSwingDots(             const char* label, float        radius,     float thickness,        const CImXVec4* color,          float           speed   );

    MLS_PUBLIC_API void ImSpinner_SpinnerSquishSquare(          const char* label, float        radius,     const CImXVec4* color,  float           speed);
#ifdef __cplusplus
}
#endif
#endif
#endif